server:
  port: 8082

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://localhost:5432/doctor_db
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
