server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8889}
  datasource:
    url: ${SPRING_DATASOURCE_URL:${USER_SERVICE_DB_URL:jdbc:postgresql://localhost:55436/user_db}}
    username: ${SPRING_DATASOURCE_USERNAME:${USER_SERVICE_DB_USERNAME:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  auth:
    jwt-issuer: clinic-appointment-system
    jwt-secret: ${APP_AUTH_JWT_SECRET:clinic-appointment-system-jwt-secret-key-32bytes-long-secret-2026}
    access-token-max-age-seconds: 3600
    refresh-token-max-age-seconds: 604800
