server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./clinic-config-repo,file:../clinic-config-repo,file:../../clinic-config-repo

encrypt:
  key: clinic-secret-key-301
