server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/home/docong2708/Documents/microservices/git_repo

encrypt:
  key: ${ENCRYPT_KEY:default_key}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always