server:
  port: 8084

spring:
  application:
    name: patient-service

  datasource:
    url: ${PATIENT_DB_URL:jdbc:postgresql://localhost:5432/patient_db}
    username: ${PATIENT_DB_USERNAME:postgres}
    password: '{cipher}1d82b74dad93ca5c16aa00769511ee325c47f46e54132b8cb46adb961d77d031'
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: '{cipher}59d9f2020bc7192ccf3367a29b5f6375dc4d21178f690deec83a590a37eaafaf'

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always
