spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${PAYMENT_DB_USERNAME:postgres}
    password: '{cipher}1d82b74dad93ca5c16aa00769511ee325c47f46e54132b8cb46adb961d77d031'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8086}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

clients:
  appointment-service:
    base-url: ${APPOINTMENT_SERVICE_URL:http://localhost:8081}
