services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: clinic-keycloak
    command: start-dev --import-realm
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export:/opt/keycloak/data/import
