spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

mail:
  from: ${spring.mail.username:noreply@clinic.local}
  from-name: ${MAIL_FROM_NAME:MSS Clinic}
  provider: SMTP

notification:
  sender:
    mock: ${NOTIFICATION_SENDER_MOCK:false}
