services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: clinic-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - clinic-network

volumes:
  rabbitmq_data:

networks:
  clinic-network:
    driver: bridge